# Generated by Django 5.1.1 on 2024-11-14 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appModelos', '0003_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
